name: New Prompt Submission
description: Suggest a new reusable AI prompt
body:
  - type: markdown
    attributes:
      value: "### Prompt Title\n<Fill in>"
  - type: textarea
    attributes:
      label: Description
      placeholder: "What is this prompt for?"
  - type: textarea
    attributes:
      label: Prompt
      placeholder: "Enter your prompt here"
  - type: textarea
    attributes:
      label: Example Output
      placeholder: "Enter the prompt output example"
  - type: textarea
    attributes:
      label: Author
      placeholder: "Feel free to provide your github username here"