name: New Prompt Submission
description: Suggest a new reusable AI prompt
body:
  - type: markdown
    attributes:
      value: "### Prompt Title\n<Fill in>"
  - type: textarea
    attributes:
      label: Description
      placeholder: "What is this prompt for?"
  - type: textarea
    attributes:
      label: Tags (comma-separated)
      description: "Add tags to help categorize this prompt. Use commas to separate multiple tags."
      placeholder: "facade, plugin, api, rest, glue, test, unit, data-import, refactoring, etc."
  - type: textarea
    attributes:
      label: Prompt
      placeholder: "Enter your prompt here"
  - type: textarea
    attributes:
      label: Example Output
      placeholder: "Enter the prompt output example"
  - type: textarea
    attributes:
      label: LLM
      description: "Which Large Language Models work well with this prompt?"
      placeholder: "Claude 3.7 Sonnet, GPT-4o, GPT-4 Turbo, etc."
  - type: textarea
    attributes:
      label: AI Assistant
      description: "Which AI coding assistants is this prompt designed for?"
      placeholder: "Windsurf, Cursor, GitHub Copilot, etc."
  - type: textarea
    attributes:
      label: Author
      placeholder: "Feel free to provide your github username here"
